# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'
variables:
  buildConfiguration: 'Release'
  
stages:
- stage: release
  jobs:
    - job: release
      steps:
      - checkout: none
      
      - task: DownloadGitHubRelease@0
        inputs:
          connection: 'github.com_Salateen'
          userRepository: 'Salateen/aspnet-sample'
          defaultVersionType: 'latest'
          downloadPath: '$(Build.ArtifactStagingDirectory)'
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'AzureServiceConnection'
          appType: 'webApp'
          WebAppName: 'aspNetsample2'
          deployToSlotOrASE: true
          ResourceGroupName: 'aspnet-sample'
          SlotName: 'production'
          packageForLinux: '$(Build.ArtifactStagingDirectory)/aspnet-sample.zip'